package com.suitcase.ui.theme

import androidx.compose.ui.graphics.Color



val Pink80 = Color(0xFFEFB8C8)
val black = Color(0xFF0A0A0A)
val white = Color(0xFFF4F1F7)
val Bluish = Color(0xFF7150AA)
val Greenish = Color(0xFF57E9A4)
val md_theme_light_primary = Color(0xFF825500)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF707470)
val md_theme_light_onPrimaryContainer = Color(0xFF291800)
val md_theme_light_secondary = Color(0xE8839E81)
val md_theme_light_onSecondary = Color(0xFF52371F)
val md_theme_light_secondaryContainer = Color(0xFFDFC09C)
val md_theme_light_onSecondaryContainer = Color(0xFF271904)
val md_theme_light_tertiary = Color(0xFF586B45)
val md_theme_light_onTertiary = Color(0xFFBE7D37)
val md_theme_light_tertiaryContainer = Color(0xFFD4EABB)
val md_theme_light_onTertiaryContainer = Color(0xFF102004)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFCBD3CB)
val md_theme_light_onBackground = Color(0xFF0A0908)
val md_theme_light_surface = Color(0xFF517051)
val md_theme_light_onSurface = Color(0xFF13100D)
val md_theme_light_surfaceVariant = Color(0xFFB4B9B4)
val md_theme_light_onSurfaceVariant = Color(0xFF312C25)
val md_theme_light_outline = Color(0xFF8B6A43)
val md_theme_light_inverseOnSurface = Color(0xFF8F837A)
val md_theme_light_inverseSurface = Color(0xFF34302A)
val md_theme_light_inversePrimary = Color(0xFF4B3311)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF44361C)
val md_theme_light_outlineVariant = Color(0xFFB6834C)
val md_theme_light_scrim = Color(0xFFAF6060)

val md_theme_dark_primary = Color(0xFFFFB951)
val md_theme_dark_onPrimary = Color(0xFF452B00)
val md_theme_dark_primaryContainer = Color(0xFF633F00)
val md_theme_dark_onPrimaryContainer = Color(0xFF16120D)
val md_theme_dark_secondary = Color(0xFF91816E)
val md_theme_dark_onSecondary = Color(0xFFAA9681)
val md_theme_dark_secondaryContainer = Color(0xFF14110B)
val md_theme_dark_onSecondaryContainer = Color(0xFFFBDEBC)
val md_theme_dark_tertiary = Color(0xFFB8CEA1)
val md_theme_dark_onTertiary = Color(0xFF0D1308)
val md_theme_dark_tertiaryContainer = Color(0xFF6B7065)
val md_theme_dark_onTertiaryContainer = Color(0xFF404B33)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF070605)
val md_theme_dark_onBackground = Color(0xFFF1EEEC)
val md_theme_dark_surface = Color(0xFF80726B)
val md_theme_dark_onSurface = Color(0xFFF7F2EE)
val md_theme_dark_surfaceVariant = Color(0xFF161411)
val md_theme_dark_onSurfaceVariant = Color(0xFFD3C4B4)
val md_theme_dark_outline = Color(0xFF9C8D7B)
val md_theme_dark_inverseOnSurface = Color(0xFF0E0C0A)
val md_theme_dark_inverseSurface = Color(0xFFEAE1D9)
val md_theme_dark_inversePrimary = Color(0xFF825500)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB951)
val md_theme_dark_outlineVariant = Color(0xFF161411)
val md_theme_dark_scrim = Color(0xFF090606)